# Similar to what a package.json file is.
[package]
name = "rust-tut"
version = "0.1.0"
authors = ["LewisWilliams"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
